# Generated by Django 6.0.2 on 2026-02-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_approved_at_blog_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='URL of AI-generated cover image', null=True),
        ),
    ]
