# Generated by Django 6.0.2 on 2026-02-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blog_cover_image_alt_blog_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='all_images',
            field=models.TextField(blank=True, default='[]', help_text='JSON array of all blog images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='URL of AI-generated cover image', max_length=1000, null=True),
        ),
    ]
