# Generated by Django 6.0.2 on 2026-02-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blog_rejection_reason_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('blog_submitted', 'Blog Submitted for Review'), ('blog_published', 'Blog Published'), ('blog_rejected', 'Blog Rejected')], max_length=50),
        ),
    ]
