# Generated by Django 6.0.2 on 2026-02-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_image_url',
            field=models.TextField(blank=True, help_text='URL or path of cover image', null=True),
        ),
    ]
